[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "REVM - Rust Ethereum Virtual Machine"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm"]
license = "MIT"
name = "revm"
repository = "https://github.com/bluealloy/revm"
version = "2.3.0"
readme = "../../README.md"

[dependencies]
arrayref  = "0.3"
auto_impl = { version = "1.0", default-features = false }
bytes = { version = "1.1", default-features = false }
futures = { version = "0.3.24", optional = true }
hashbrown = { version = "0.13" }
hex = { version = "0.4", optional = true }
num_enum = { version = "0.5", default-features = false } # used for SpecId from u8 cast
primitive-types = { version = "0.12", default-features = false, features = ["rlp"] }
revm_precompiles = { path = "../revm_precompiles", version = "1.1.1", default-features = false }
rlp = { version = "0.5", default-features = false } # used for create2 address calculation
ruint = { version = "1.7.0", features = ["primitive-types", "rlp"] }
serde = { version = "1.0", features = ["derive","rc"], optional = true }
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"], optional = true }
web3 = { git = "https://github.com/tomusdrw/rust-web3", version = "0.19", optional = true }

# sha3 keccak hasher
sha3 = { version = "0.10", default-features = false, features = []}

[features]
default = ["std", "secp256k1"]
dev = ["memory_limit", "optional_block_gas_limit", "optional_eip3607", "optional_gas_refund"]
memory_limit = []
no_gas_measuring = []
optional_block_gas_limit = []
optional_eip3607 = []
optional_gas_refund = []
std = ["bytes/std", "num_enum/std", "primitive-types/std", "rlp/std"]
secp256k1 = ["revm_precompiles/secp256k1"]
k256 = ["revm_precompiles/k256_ecrecover"]
web3db = ["futures", "tokio", "web3"]
with-serde = ["serde", "primitive-types/serde", "hex", "hex/serde", "hashbrown/serde"]
